- hosts: wkstn
  vars:
    sysmon_download_url_base: "https://download.sysinternals.com/files"
    sysmon_install_location: "c:\\windows\\sysmon"
    sysmon_download_file: "Sysmon" 
    file_ext: ".zip"
    sysmon_config_url: "https://raw.githubusercontent.com/SwiftOnSecurity/sysmon-config/master/sysmonconfig-export.xml"
    winlogbeat_download_url_base: "https://artifacts.elastic.co/downloads/beats/winlogbeat/winlogbeat-7.10.0-windows-x86_64.zip"
    winlogbeat_install_location: "c:\\windows\\winlogbeat"
    winlogbeat_download_file: "winlogbeat" 
    winlogbeat_config: "C:\\Windows\\winlogbeat\\winlogbeat.yml"
    winlogbeat_config_src: "/mnt/c/tools/Automation/ansible/winlogbeat.yml"
    temp_location: "C:\\Windows\\Temp"
  gather_facts: no
  tasks:      
    - name: '[Install Winlogbeat] - Run winlogbeat'
      win_shell: 'powershell -exec bypass -nop -file "{{ winlogbeat_install_location }}\\install-service-winlogbeat.ps1" >> c:\windows\winlogbeat\winlogbeat-install-logs.txt'
      when: result.state is not defined
      
    - name: '[Install Winlogbeat] - Check winlogbeat service'
      win_service:
        name: winlogbeat
        state: started